name: Webhook Proxy
version: "1.0.0"
slug: webhook_proxy_addon
description: Wandelt einen GET-Webhook in einen POST-Webhook fuer Home Assistant
startup: services
boot: auto
host_network: true
homeassistant_api: false
options: {}
schema: {}
ports:
  8888/tcp: 8888
